name: CSF407_2026_Oracle

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.10
  - numpy>=1.24
  - matplotlib>=3.7
  - scipy>=1.10
  - pip
  - pip:
      - imageio[ffmpeg]
      - imageio-ffmpeg
