"""
config.py
Centralized configuration for Oracle Agent — CS F407 AI Assignment
"""

import random as _random

RANDOM_SEED = None

if RANDOM_SEED is not None:
    _random.seed(RANDOM_SEED)

GRID_ROWS = _random.randint(8, 10)
GRID_COLS = _random.randint(8, 10)

CELL_LAND = 'L'
CELL_VOLCANO = 'V'
CELL_WATER = 'W'
CELL_WALL = 'B'
CELL_START = 'S'
CELL_GOAL = 'G'

WALK_TIME_COST = 2
JUMP_TIME_COST = 3
TURN_COST = 1
WALL_TURN_COST = 1

AGENT_START_LIVES = 4
AGENT_MIN_LIVES = 0

HAZARDS_ON_PATH = 4
VOLCANOES_ON_PATH = 2
WATERS_ON_PATH = 2

NON_PATH_HAZARD_RATIO = 0.50
NON_PATH_LAND_RATIO = 0.40
NON_PATH_WALL_RATIO = 0.10

P_VOLCANO_BERNOULLI = 0.40
P_WATER_BERNOULLI = 0.40

PRIOR_VOLCANO = P_VOLCANO_BERNOULLI * (1 - P_WATER_BERNOULLI)
PRIOR_WATER = (1 - P_VOLCANO_BERNOULLI) * P_WATER_BERNOULLI
PRIOR_LAND = P_VOLCANO_BERNOULLI * P_WATER_BERNOULLI
PRIOR_WALL = (1 - P_VOLCANO_BERNOULLI) * (1 - P_WATER_BERNOULLI)

CPT = {
    CELL_VOLCANO: (0.85, 0.60),
    CELL_WATER: (0.01, 0.85),
    CELL_LAND: (0.10, 0.05),
    CELL_WALL: (0.05, 0.01),
}

MAX_SCANS_PER_CELL = 4
RISK_SCAN_THRESHOLD = 0.35
RISK_AVOID_THRESHOLD = 0.70

COLOR_LAND = '#90EE90'
COLOR_VOLCANO = '#FF4500'
COLOR_WATER = '#4169E1'
COLOR_WALL = '#696969'
COLOR_START = '#FFD700'
COLOR_GOAL = '#32CD32'
COLOR_PATH = '#FFA500'
COLOR_AGENT = '#1E1E1E'

COLOR_WALK_ARROW = '#000000'
COLOR_JUMP_ARROW = '#800080'
COLOR_DAMAGE_ARROW = '#FF0000'

BELIEF_VOLCANO_THRESH = 0.40
BELIEF_WATER_THRESH = 0.40
BELIEF_LAND_THRESH = 0.50
COLOR_UNKNOWN = '#AAAAAA'
COLOR_SCAN_BORDER = '#FFD700'

OUTPUT_DIR = 'outputs'
GROUND_TRUTH_PNG = 'ground_truth_trajectory.png'
INITIAL_GRID_PNG = 'initial_grid.png'
SIMULATION_GIF = 'simulation.gif'
SIMULATION_MP4 = 'simulation.mp4'
FRAME_DIR = 'frames'
GIF_FRAME_DURATION_MS = 400
FIGURE_DPI = 120